settings:
  disabled_events: []
  whitelisted_events:
    - comments
    - create_repo
    - fork
    - issues
    - member
    - pr
    - release
    - review
    - star
    - wiki
    - push
  max_lines: 7
  commit_username: albusbot
  commit_email: bot@nishantwrp.com
  commit_msg: "chore: fetch latest github activity"
