name: Fetch latest tweets
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "TWITTER"
          feed_list: "https://rss.app/feeds/HZNyHs5FRDSrVL00.xml"
          commit_message: "Updated with the latest tweets"
          committer_username: "albusbot"
          committer_email: "bot@nishantwrp.com"
